services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - stations-management
    networks:
      - elytra

  stations-management:
    container_name: stations-management
    build:
      context: ./stations-management
      dockerfile: Dockerfile.prod
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
    networks:
      - elytra

networks:
  elytra:
    driver: bridge
