version: "3.8"

services:
  k6:
    image: grafana/k6:latest
    container_name: k6-load-testing
    networks:
      - elytra
    volumes:
      - ./load-testing/scripts:/scripts:ro
      - ./load-testing/results:/results
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM=true
    depends_on:
      - nginx
      - stations-management
      - prometheus
    profiles:
      - load-testing
    command: ["sleep", "infinity"]

  k6-prometheus:
    image: grafana/k6:latest
    container_name: k6-prometheus-writer
    networks:
      - elytra
    volumes:
      - ./load-testing/scripts:/scripts:ro
    environment:
      - K6_OUT=experimental-prometheus-rw
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM=true
      - K6_PROMETHEUS_RW_PUSH_INTERVAL=5s
    depends_on:
      - prometheus
      - nginx
      - stations-management
    profiles:
      - load-testing-continuous
    restart: "no"

networks:
  elytra:
    external: true

volumes:
  k6_results:
