{
 "title": "k6 Prometheus",
 "description": "Visualize k6 OSS results stored in Prometheus",
 "tags": [
  "prometheus",
  "k6"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus DS", "query": "prometheus" },
   { "name": "testid", "label": "Test ID", "query": { "query": "label_values(testid)" } },
   { "name": "quantile_stat", "label": "Trend Metrics Query", "query": { "query": "metrics(k6_http_req_duration_)" } },
   { "name": "adhoc_filter", "label": "AdhocFilter" }
  ]
 },
 "panels": [
  {
   "title": "Performance Overview",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(k6_vus{testid=~\"$testid\"})",
     "legendFormat": "vus"
    },
    {
     "expr": "avg(k6_http_req_duration_$quantile_stat{testid=~\"$testid\"})",
     "legendFormat": "http_req_duration_$quantile_stat"
    },
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "http_req_s"
    },
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"false\"}[$__rate_interval]))",
     "legendFormat": "http_req_s_errors"
    }
   ]
  },
  {
   "title": "HTTP Latency Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(k6_http_req_blocked_$quantile_stat{testid=~\"$testid\"})",
     "legendFormat": "http_req_blocked_$quantile_stat"
    },
    {
     "expr": "avg(k6_http_req_tls_handshaking_$quantile_stat{testid=~\"$testid\"})",
     "legendFormat": "http_req_tls_handshaking_$quantile_stat"
    },
    {
     "expr": "avg(k6_http_req_sending_$quantile_stat{testid=~\"$testid\"})",
     "legendFormat": "http_req_sending_$quantile_stat"
    },
    {
     "expr": "avg(k6_http_req_waiting_$quantile_stat{testid=~\"$testid\"})",
     "legendFormat": "http_req_waiting_$quantile_stat"
    },
    {
     "expr": "avg(k6_http_req_receiving_$quantile_stat{testid=~\"$testid\"})",
     "legendFormat": "http_req_receiving_$quantile_stat"
    },
    {
     "expr": "avg(k6_http_req_duration_$quantile_stat{testid=~\"$testid\"})",
     "legendFormat": "http_req_duration_$quantile_stat"
    }
   ]
  },
  {
   "title": "HTTP Latency Stats",
   "type": "timeseries",
   "description": "Select a different Stat to change the query",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(k6_http_req_duration_$quantile_stat{testid=~\"$testid\"})",
     "legendFormat": "http_req_duration_$quantile_stat"
    },
    {
     "expr": "avg(k6_http_req_duration_$quantile_stat{testid=~\"$testid\", expected_response=\"true\"})",
     "legendFormat": "success_http_req_duration_$quantile_stat"
    },
    {
     "expr": "avg(k6_http_req_duration_$quantile_stat{testid=~\"$testid\", expected_response=\"false\"})",
     "legendFormat": "errors_http_req_duration_$quantile_stat"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "http_req_s"
    },
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"false\"}[$__rate_interval]))",
     "legendFormat": "http_req_s_errors"
    },
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"true\"}[$__rate_interval]))",
     "legendFormat": "http_req_s_success"
    }
   ]
  }
 ]
}