global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "stations-management"
    static_configs:
      - targets: ["stations-management:8080"]
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
