global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "stations-management"
    static_configs:
      - targets: ["stations-management:8080"]
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s

  - job_name: "nginx"
    static_configs:
      - targets: ["nginx:80"]
    metrics_path: "/nginx_status"
    scrape_interval: 5s

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 5s
