name: Deploy Production Docker on PR merge to main

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy-prod-docker:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Make deploy script executable
        run: chmod +x deploy.sh

      - name: Run deployment script
        run: ./deploy.sh
