name: Update Submodule Reference
on:
  repository_dispatch:
    types: [submodule-updated]

permissions:
  contents: write

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo & sub-modules
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_PAT }}
          fetch-depth: 0
          submodules: recursive

      - name: Git identity
        run: |
          git config --global user.name  'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'

      - name: Switch to dev
        run: git checkout dev

      - name: Find sub-module path
        id: path
        run: |
          REPO_NAME=$(basename "${{ github.event.client_payload.submodule_name }}")
          SUB_PATH=$(git config -f .gitmodules --get-regexp path | grep "$REPO_NAME" | awk '{print $2}')
          echo "path=$SUB_PATH" >>"$GITHUB_OUTPUT"

      - name: Update pointer
        run: |
          cd "${{ steps.path.outputs.path }}"
          git fetch origin
          git checkout ${{ github.event.client_payload.commit_sha }}
          cd -
          git add "${{ steps.path.outputs.path }}"
          if ! git diff --cached --quiet; then
            git commit -m "Update ${{
              steps.path.outputs.path }} → ${{ github.event.client_payload.commit_sha }}"
            git push \
              "https://x-access-token:${{ secrets.BOT_PAT }}@github.com/${{ github.repository }}.git" \
              HEAD:dev
          fi

